repos:
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.1.1
    hooks:
    - id: autoflake
      types: [python]
      require_serial: true
      args:
        - "--in-place"
        - "--expand-star-imports"
        - "--remove-duplicate-keys"
        - "--remove-unused-variables"
        - "--remove-all-unused-imports"
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
    -   id: black-jupyter
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      language_version: python3.9
      args:
      - '--max-line-length=100'
      - '--ignore=E203,E266,E501,W503,F403,F401,E731'
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace